;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file located at
;; https://gitlab.com/zzamboni/dot-doom/-/blob/master/doom.org
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
;; (setq user-full-name "John Doe"
;;      user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
;; (setq doom-theme 'doom-one)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
;; (setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
;; (setq display-line-numbers-type t)

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

(setq user-full-name "Evie Gauthier"
      user-mail-address "evie@gauthier.id")

(defun unicode-fonts-setup-h (frame)
  "Run unicode-fonts-setup, then remove the hook."
  (progn
    (select-frame frame)
    (unicode-fonts-setup)
    (message "Removing unicode-fonts-setup to after-make-frame-functions hook")
    (remove-hook 'after-make-frame-functions 'unicode-fonts-setup-h)
    ))

(add-hook 'after-make-frame-functions 'unicode-fonts-setup-h nil)

(setq auto-dark-allow-osascript t)
(use-package! auto-dark
  :defer t
  :init
  ;; Configure themes
  (setq! auto-dark-themes '((doom-one) (doom-one-light)))
  ;; Disable doom's theme loading mechanism (just to make sure)
  (setq! doom-theme nil)
  ;; Declare that all themes are safe to load.
  ;; Be aware that setting this variable may have security implications if you
  ;; get tricked into loading untrusted themes (via auto-dark-mode or manually).
  ;; See the documentation of custom-safe-themes for details.
  (setq! custom-safe-themes t)
  ;; Enable auto-dark-mode at the right point in time.
  ;; This is inspired by doom-ui.el. Using server-after-make-frame-hook avoids
  ;; issues with an early start of the emacs daemon using systemd, which causes
  ;; problems with the DBus connection that auto-dark mode relies upon.
  (defun my-auto-dark-init-h ()
    (auto-dark-mode)
    (remove-hook 'server-after-make-frame-hook #'my-auto-dark-init-h)
    (remove-hook 'after-init-hook #'my-auto-dark-init-h))
  (let ((hook (if (daemonp)
                  'server-after-make-frame-hook
                'after-init-hook)))
    ;; Depth -95 puts this before doom-init-theme-h, which sounds like a good
    ;; idea, if only for performance reasons.
    (add-hook hook #'my-auto-dark-init-h -95)))

(setq display-line-numbers-type t)

(setq auto-save-default t
      make-backup-files t
      delete-by-moving-to-trash t)

(setq doom-modeline-enable-word-count t)

(setq! doom-unicode-font (font-spec :family "MesloLGS NF" :size 12))

(doom-load-envvars-file "~/.doom.d/myenv")
(after! auth-source
  (setq auth-sources (nreverse auth-sources)))

(require 'age)
(age-file-enable)

(after! epa-file
  (setq epg-gpg-program (executable-find "gpg"))
  (setq epa-file-encrypt-to '("A6AC158CED6A07FDA8883488FDAE4752DD939E6E")))

(after! dired-preview
    ;; Default values for demo purposes
    (setq dired-preview-delay 0.2)
    (setq dired-preview-max-size (expt 2 100))
    (setq dired-preview-ignored-extensions-regexp
        (concat "\\."
                "\\(mkv\\|webm\\|mp4\\|mp3\\|ogg\\|m4a"
                "\\|gz\\|zst\\|tar\\|xz\\|rar\\|zip"
                "\\|iso\\|epub\\)"))

    ;; Enable `dired-preview-mode' in a given Dired buffer or do it
    ;; globally:
    (dired-preview-global-mode 1)
    (dired-preview-trigger-on-start 1)
)

(setq org-directory "~/Sync/")

(setq org-agenda-files (directory-files-recursively "~/Sync/" "\\.org$"))

(add-hook! org-mode (electric-indent-local-mode -1))

(after! org-modern
  (setq org-modern-star 'replace))

(after! org-agenda
  (setq org-agenda-include-diary t)
  (setq org-agenda-prefix-format
        '((agenda . " %i %(vulpea-agenda-category 12)%?-12t% s")
          (todo . " %i %(vulpea-agenda-category 12) ")
          (tags . " %i %(vulpea-agenda-category 12) ")
          (search . " %i %(vulpea-agenda-category 12) ")))

  (defun vulpea-agenda-category (&optional len)
    "Get category of item at point for agenda.

Category is defined by one of the following items:

- CATEGORY property
- TITLE keyword
- TITLE property
- filename without directory and extension

When LEN is a number, resulting string is padded right with
spaces and then truncated with ... on the right if result is
longer than LEN.

Usage example:

  (setq org-agenda-prefix-format
        '((agenda . \" %(vulpea-agenda-category) %?-12t %12s\")))

Refer to `org-agenda-prefix-format' for more information."
    (let* ((file-name (when buffer-file-name
                        (file-name-sans-extension
                         (file-name-nondirectory buffer-file-name))))
           (title (vulpea-buffer-prop-get "title"))
           (category (org-get-category))
           (result
            (or (if (and
                     title
                     (string-equal category file-name))
                    title
                  category)
                "")))
      (if (numberp len)
          (s-truncate len (s-pad-right len " " result))
        result)))
  )

(use-package! holidays
  :after org-agenda
  :config
  (setq calendar-holidays
        (append '((holiday-fixed 1 1 "New Year's Day")
                  (holiday-fixed 2 14 "Valentine's Day")
                  (holiday-fixed 4 1 "April Fools' Day")
                  (holiday-fixed 10 31 "Halloween")
                  (holiday-easter-etc)
                  (holiday-fixed 12 25 "Christmas")
                  (solar-equinoxes-solstices)))))

(use-package! org-super-agenda
  :after org-agenda
  :config
  (setq org-super-agenda-groups '((:auto-dir-name t)))
  (org-super-agenda-mode))

(setq org-roam-directory (file-truename "~/Sync"))
(setq +org-roam-open-buffer-on-find-file t)
(setq org-roam-database-connector 'sqlite)

(use-package! websocket
    :after org-roam)

(use-package! org-roam-ui
    :after org-roam ;; :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))

(after! org
  (use-package! ox-extra
    :config
    (ox-extras-activate '(latex-header-blocks ignore-headlines))))

(after! org
  ;; Import ox-latex to get org-latex-classes and other funcitonality
  ;; for exporting to LaTeX from org
  (use-package! ox-latex
    :init
    ;; code here will run immediately
    :config
    ;; code here will run after the package is loaded
    (setq org-latex-pdf-process
          '("pdflatex -interaction nonstopmode -output-directory %o %f"
            "bibtex %b"
            "pdflatex -interaction nonstopmode -output-directory %o %f"
            "pdflatex -interaction nonstopmode -output-directory %o %f"))
    (setq org-latex-with-hyperref nil) ;; stop org adding hypersetup{author..} to latex export
    ;; (setq org-latex-prefer-user-labels t)

    ;; deleted unwanted file extensions after latexMK
    (setq org-latex-logfiles-extensions
          (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf" "acn" "acr" "alg" "glg" "gls" "ist" "xmpi")))

    (unless (boundp 'org-latex-classes)
      (setq org-latex-classes nil))))

(setq ob-powershell-powershell-command "pwsh")
(org-babel-do-load-languages
 'org-babel-load-languages
 (quote (
         ;; ...
         (powershell . t)
         (d2 . t))))

(setq d2-location "/opt/homebrew/bin/d2")

(use-package! org-auto-tangle
  :defer t
  :hook (org-mode . org-auto-tangle-mode)
  :config
  (setq org-auto-tangle-default t))

(setq lsp-warn-no-matched-clients nil)

(use-package! eat
  :hook (eshell-mode . eat-eshell-mode))

(after! with-editor
  (setq with-editor-emacsclient-executable
        "/opt/homebrew/bin/emacsclient"))

(after! magit
  (magit-delta-mode +1))

(use-package! copilot-chat
  :after (org markdown-mode)
  :bind (("C-c a c" . copilot-chat-transient)
         ("C-c a C" . copilot-chat-display)
         ("C-c a i" . copilot-chat-goto-input)
         ("C-c a e" . copilot-chat-explain)
         ("C-c a r" . copilot-chat-review)
         ("C-c a f" . copilot-chat-fix))
  :config
  (setq copilot-chat-backend 'curl
        copilot-chat-frontend 'org
        copilot-chat-follow t
        copilot-chat-default-save-dir "~/.doom.d/copilot-chat/")

  ;; Safer than hard-coding a possibly unavailable model name.
  ;; After first auth, use:
  ;;   M-x copilot-chat-set-model
  ;; If models seem stale, run:
  ;;   M-x copilot-chat-reset-models
  ;;
  ;; If you really want to hard-code one later, uncomment:
  ;; (setq copilot-chat-default-model "claude-sonnet-4")
  )

(use-package! mcp
  :defer t
  :init
  (require 'auth-source)

  (defun my/get-github-token ()
    "Return GitHub token from auth-source."
    (let* ((match (car (auth-source-search
                        :host "api.github.com"
                        :require '(:secret)
                        :max 1)))
           (secret (when match (plist-get match :secret))))
      (cond
       ((functionp secret) (funcall secret))
       ((stringp secret) secret)
       (t nil))))

  (defun my/get-github-token-or-error ()
    "Return GitHub token from auth-source, or error."
    (or (my/get-github-token)
        (user-error "No GitHub token found in ~/.authinfo.gpg for api.github.com")))

  (setq mcp-hub-servers
        `(("filesystem" . (:command "npx"
                           :args ("-y" "@modelcontextprotocol/server-filesystem")
                           :roots ("~/projects" "~/git" "~/Sync")))

          ("github" . (:command "docker"
                       :args ("run" "-i" "--rm"
                              "-e" "GITHUB_PERSONAL_ACCESS_TOKEN"
                              "-e" "GITHUB_TOOLSETS=default,actions"
                              "ghcr.io/github/github-mcp-server")
                       :env (:GITHUB_PERSONAL_ACCESS_TOKEN
                             ,(my/get-github-token-or-error))))))

  :config
  (require 'mcp-hub))

;; Optional: auto-start configured MCP servers after startup.
;; Leave commented until you've verified both servers work manually.
;;
;; (after! mcp
;;   (add-hook 'after-init-hook #'mcp-hub-start-all-server))

(add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode))
(put 'dockerfile-image-name 'safe-local-variable #'stringp)

(defun plain-pipe-for-process () (setq-local process-connection-type nil))
(add-hook 'compilation-mode-hook 'plain-pipe-for-process)

(use-package! iedit
  :defer
  :config
  (set-face-background 'iedit-occurrence "Magenta")
  :bind
  ("C-;" . iedit-mode))

(defmacro zz/measure-time (&rest body)
  "Measure the time it takes to evaluate BODY."
  `(let ((time (current-time)))
     ,@body
     (float-time (time-since time))))
