#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config debug_output on

# # bar settings
# yabai -m config status_bar on
# yabai -m config status_bar_text_font "Fira Code:Regular:12.0"
# yabai -m config status_bar_icon_font "FontAwesome:Regular:12.0"
# yabai -m config status_bar_background_color 0xff202020
# yabai -m config status_bar_foreground_color 0xffa8a8a8
# yabai -m config status_bar_space_icon_strip I II III IV V VI VII VIII IX X
# yabai -m config status_bar_power_icon_strip  
# yabai -m config status_bar_space_icon 
# yabai -m config status_bar_clock_icon 

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autoraise
yabai -m config window_placement second_child
yabai -m config window_topmost off #off
yabai -m config window_opacity on #off
# yabai -m config window_opacity_duration 0.0
yabai -m config window_shadow off
yabai -m config window_border on #off
yabai -m config window_border_placement inset
yabai -m config window_border_width 10
yabai -m config window_border_radius 2
yabai -m config active_window_border_color 0xFF40FF00
yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config insert_window_border_color 0xffd75f5f
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.6
yabai -m config split_ratio 0.50
yabai -m config auto_balance on #off
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout bsp
yabai -m config external_bar all:27:0
yabai -m config top_padding 5 #10
yabai -m config bottom_padding 5 #10
yabai -m config left_padding 5 #10
yabai -m config right_padding 5 #10
yabai -m config window_gap 5 #10

# Space Labels

#python3 ./.config/yabai/yabaictl.py update-spaces

#yabai -m space 1 --label main
#yabai -m space 2 --label code
#yabai -m space 3 --label term
#yabai -m space 4 --label chat
#yabai -m space 5 --label spotify 

#yabai -m space main --display 1
#yabai -m space chat --display 2
#yabai -m space code --display 3
#yabai -m space term --display 3
#yabai -m space term --move next
#yabai -m space spotify --display 3
#yabai -m space spotify --move next
#yabai -m space spotify --move next

yabai -m space --create
yabai -m space 1 --label main
yabai -m space 2 --label media
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^Music$" space=media

# Rules

#yabai -m rule --add app=iTerm space=term
#yabai -m rule --add app=Code space=code
#yabai -m rule --add app=Safari space=main
#yabai -m rule --add app=Firefox space=main
#yabai -m rule --add app="News Explorer" space=news
#yabai -m rule --add app=Discord space=chat
#yabai -m rule --add app=Franz space=chat
#yabai -m rule --add app=Ferdi space=chat
#yabai -m rule --add app=Spotify space=spotify

#yabai -m rule --add app="code" display=2
#yabai -m rule --add app="iTerm" display=2

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off layer=above
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off layer=above
yabai -m rule --add label="Firefox" app="^Firefox$" title="^Opening .*$" manage=off layer=above
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off layer=above
yabai -m rule --add label="App Store" app="^App Store$" manage=off layer=above
yabai -m rule --add label="Reminders" app="^Reminders$" manage=off layer=above
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off layer=above
yabai -m rule --add app="^System Preferences$" manage=off border=off layer=above
yabai -m rule --add app="^Preview$" manage=off border=off layer=above
yabai -m rule --add app="mpv" manage=off border=off layer=above
#yabai -m signal --add event=space_changed \
#    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"spaces-jsx\"'"

yabai -m signal --add event=application_launched \
    action="${HOME}/.config/yabai/float.sh"
yabai -m signal --add event='space_changed' action="${HOME}/.config/yabai/autoclose.sh"
#yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".resizable == 0 and .floating == 0" && yabai -m window $YABAI_WINDOW_ID --toggle float'
#find "${HOME}/.config/yabai" -type f -perm +111 -exec {} \;

### Übersicht - Simple-Bar

# Refresh spaces widget on space change
yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# Refresh spaces widget on display focus change
yabai -m signal --add event=display_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# Refresh spaces widget on window resize
yabai -m signal --add event=window_resized action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# Refresh process widget on space change
yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"

# Refresh process widget on when focused application changes
yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Refresh spaces widget on when focused application changes
yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget on when focused application changes
yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Refresh spaces widget on when focused application changes
yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget on when an application window is closed
yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Refresh spaces widget on when an application window is closed
yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget when current window title changes
yabai -m signal --add event=window_title_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"

## https://github.com/koekeishiya/yabai/issues/681#issuecomment-711314021

tempDir=/tmp/yabai-tiling-floating-toggle
[ -d $tempDir ] && rm -rf $tempDir
mkdir $tempDir

echo "yabai configuration loaded.."